# Generated by configure from .in at Sun Jan 23 19:29:20 CET 2005

CC	= gcc
LD	= gcc

CFLAGS	= -g -Wall
CFLAGS	+= -I.
LDFLAGS	= libinterrupt.a
HEADERS = queue.h mythread.h RR.h RRF.h RRFI.h


OBJS	= queue.o mythreadlib.o RR.o RRF.o RRFI.o

LIBS	=

SRCS	= $(patsubst %.o,%.c,$(OBJS))

PRGS	= main

all: libinterrupt.a $(PRGS)

libinterrupt.a: interrupt.o
	ar -rv libinterrupt.a interrupt.o

%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) -c $*.c $(INCLUDE) -o $@ $(LIBS)

$(PRGS): $(OBJS)
$(PRGS): $(LIBS)
$(PRGS): % : %.o
	$(CC) $(CFLAGS) -o $@ $< $(OBJS) $(LDFLAGS) $(LIBS)

clean:
	-rm -f *.o *.a *~ $(PRGS)
